awslabs/mountpoint-s3-csi-driver

docs/install.md

Mostly just copyediting and a few small missing things.

Update install docs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_request.md

* Adding issue templates for the repo

Adding issue templates

---

.github/workflows/e2e-tests.yaml

- Build/push image once and use it in all tests (kops/eks - x86/arm)
- Wait for all tests (kops/eks - x86/arm) before promoting image to private `s3-csi-driver` repo
___

run tests on the same image, promote image if all tests are successful

---

.github/workflows/release.yaml

* Adding copy to public ECR repo as a part of release workflow

Add changes to copy image to public ECR repo

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

Staging v1.1.0 release

---

.github/workflows/e2e-tests.yaml

Run e2e workflow for all pushes to main

---

.github/workflows/release.yaml

* Quickfix for release workflow

Quickfix for release workflow

---

.github/ISSUE_TEMPLATE/bug_report.md

* point customers to Mountpoint repo if it's a filesystem related bug

Adding reference to MP

---

examples/kubernetes/static_provisioning/README.md
examples/kubernetes/static_provisioning/multiple_buckets_one_pod.yaml

* https://github.com/awslabs/mountpoint-s3-csi-driver/issues/114
* adding example for multiple buckets in one pod

Adding example for multiple buckets in one pod

---

Dockerfile

Upgrading Mountpoint version to 1.3.2

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

* Updating helm charts and kustomize to v1.2.0

Update version in helm charts and kustomize

---

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml

*Issue #122 
add imagePullSecrets support for private registries (optional)

Add imagePullSecrets support

---

Dockerfile

Upgrading MP to v1.4.0

---

docs/install.md

* add `--role-only` to sa creation cmd

Fixing sa creation cmd

---

CHANGELOG.md
Makefile
README.md

Staging v1.3.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

* merge v1.3.0 changes back to main

Update main to v1.3.0

---

charts/aws-mountpoint-s3-csi-driver/values.yaml
docs/install.md

* https://github.com/awslabs/mountpoint-s3-csi-driver/issues/109
* (we already support tolerations, just not taints for them in the values.yaml which is what this PR is for)
* allow support for tolerating taints

Support taints in helm chart

---

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml

We need to run this only on a few nodes or a group of nodes and not every node.
Add a nodeSelector to the values flie and in the node manifest.

add nodeSelector to run on a selection of nodes

---

CHANGELOG.md
Dockerfile
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

* patch fix for Mountpoint version v1.4.1

Staging v1.3.1 release

---

CHANGELOG.md
Dockerfile
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

* merge patch release v1.3.1 updates to main

v1.3.1 release (#151)

---

.github/workflows/e2e-tests.yaml
tests/e2e-kubernetes/README.md
tests/e2e-kubernetes/scripts/eksctl.sh
tests/e2e-kubernetes/scripts/run.sh

*Issue #, if available:* #86
*Description of changes:* Add an EKS Bottlerocket cluster to the integration test matrix.

Add integration tests for Bottlerocket

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* Release 1.4.0

v1.4.0 release

---

CHANGELOG.md
Makefile
README.md

*Issue #, if available:* NA
*Description of changes:* Bumping version to v1.5.0

Staging v1.5.0 release

---

CHANGELOG.md
Makefile
README.md

*Description of changes:* Bumping version to 1.5.1

Staging v1.5.1 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* Merge 1.5.1 release

v1.5.1 release

---

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml

Add node affinity + no schedule on fargate

feat: add node affinity + no schedule on fargate

---

charts/aws-mountpoint-s3-csi-driver/values.yaml

*Issue #, if available:* NA
*Description of changes:* Updating the sidecar container images from public ecr.

Update sidecar versions to latest

---

Dockerfile

*Description of changes:* Pull in mountpoint v1.6.0 release

Update mountpoint to v1.6.0 release

---

CHANGELOG.md
Makefile
README.md

*Description of changes:* Bumping versions to 1.6.0

Stage v1.6.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* Merge 1.6 release branch

Merge v1.6.0 release

---

Dockerfile

Update mountpoint to v1.7.2 release

Update mountpoint to v1.7.2 release

---

CHANGELOG.md
Makefile
README.md

*Description of changes:* Bumping versions to 1.7.0

Stage v1.7.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* Merge v1.7.0 release

Merge v1.7.0 release

---

docs/LOGGING.md

First pass at logging documentation.
Currently, there is no documentation about how to get the logs for troubleshooting at all. This should provides basic guidance for that.

Add logging documentation

---

charts/aws-mountpoint-s3-csi-driver/values.yaml

*Issue #, if available:* https://github.com/awslabs/mountpoint-s3-csi-driver/issues/212
Include comments for how to use regional ECR repositories.

Add information to helm chart for how to configure regional ECR repos

---

.github/workflows/e2e-tests.yaml
.github/workflows/unit-tests.yaml

*Description of changes:* For features that take longer to implement, we want to ensure that all test workflows are ran.

Run test workflows on feature branches

---

pkg/driver/mount.go

[174](https://github.com/awslabs/mountpoint-s3-csi-driver/issues/174)
Since it's unclear why the driver cannot read `/host/proc/mounts` (with Karpenter) at the first time, retry to read `/host/proc/mounts` will success.
It is necessary to keep investigating the root cause, but this issue currently affects many Karpenter (and possibly other) users. To prevent users from having to manually restart `s3-csi-node-xxx` every time, it is better to solve the issue by retrying the read in the code.

Fix cannot mount PVC in driver (#174)

---

Dockerfile

Update Mountpoint to v1.8.0 release

---

CHANGELOG.md
Makefile
README.md

Stage v1.8.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

Merge v1.8.0 release

---

pkg/driver/credential.go
pkg/driver/mount.go
pkg/driver/version.go
pkg/driver/version_test.go

Add authentication source to user-agent

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

Stage v1.8.1 release

---

go.mod
pkg/driver/credential.go
pkg/driver/driver.go

Pod-level identity improvements

---

deploy/kubernetes/base/csidriver.yaml
deploy/kubernetes/base/node-daemonset.yaml
deploy/kubernetes/base/node-serviceaccount.yaml

Update Kustomization manifest

---

Dockerfile

Update Mountpoint to v1.9.1

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* Release 1.9.0

v1.9.0 release

---

.github/workflows/e2e-tests.yaml
tests/e2e-kubernetes/scripts/run.sh

Add Kubernetes v1.31 to testing matrix

---

pkg/driver/node/mounter/credential_provider.go

Link to documentation if Pod info is missing

---

Dockerfile

Updating bundled Mountpoint version to latest available release.

Update Mountpoint to 1.10.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

Publish v1.10.0 release.
Previous release example: #266

v1.10.0 release

---

Dockerfile

Updating bundled Mountpoint version to latest available release.

Update Mountpoint to 1.12.0 release

---

Dockerfile

Update Mountpoint to v1.13.0 release

---

charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/base/node-daemonset.yaml

Update anti-affinity rules for incompatible compute types

---

CHANGELOG.md
Makefile
README.md

Stage v1.11.0 release

---

.github/workflows/release.yaml
.github/workflows/unit-tests.yaml

Fixup based on comments on previous PR, and test that PRs from forks now work properly

Add more initial support for merge_queues

---

CHANGELOG.md
Dockerfile

Update Mountpoint to v1.14.0 release

---

CHANGELOG.md
Makefile
README.md

*Description of changes:* Stage release for v1.12.0

Staging v1.12.0 release

---

charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* v1.12.0 release

v1.12.0 release

---

.github/matrix.yaml
.github/workflows/e2e-tests.yaml

*Description of changes:* Builds were segfaulting (https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/12986609886/job/36213821655).

Build on ubuntu22-04

---

pkg/driver/node/envprovider/provider.go
pkg/driver/node/envprovider/provider_test.go
pkg/driver/node/mounter/credential_provider.go
pkg/driver/node/mounter/mount_credentials.go
pkg/driver/node/mounter/mounter.go
pkg/driver/node/mounter/systemd_mounter.go
pkg/driver/node/mounter/systemd_mounter_test.go

Splitted out of https://github.com/awslabs/mountpoint-s3-csi-driver/pull/328.
---

Add `envprovider` package for accessing environment variables

---

pkg/driver/driver.go

We added `PodMounter` via https://github.com/awslabs/mountpoint-s3-csi-driver/pull/368, and experimental Helm feature-flag for `PodMounter` related manifests via https://github.com/awslabs/mountpoint-s3-csi-driver/pull/372. This PR ties these changes together and enables `PodMounter` implementation if experimental Helm feature-flag is enabled.
---

Use `PodMounter` if `MOUNTER_KIND` is set to `pod`

---

cmd/aws-s3-csi-mounter/csimounter/csimounter.go

This is a temporary workaround in `csimounter` to create a cache folder in caching is enabled. We should ideally create a volume in the Mountpoint Pod and use that as cache, but until we implement that, this workaround allows us to pass end-to-end tests that rely on cache.
---

Use a tempdir for cache if caching is enabled in `csimounter`

---

.github/workflows/delete-cluster.yaml
tests/e2e-kubernetes/scripts/eksctl.sh
tests/e2e-kubernetes/scripts/kops.sh
tests/e2e-kubernetes/scripts/run.sh

Ensure to have `kops_` and `eksctl_` prefixes in bash functions for CI

---

Dockerfile

Update mountpoint to v1.15.0 release

Bump Mountpoint version to 1.15.0

---

.github/workflows/release.yaml

*Description of changes:* Remove image promotion from release workflow

Remove image promotion from release workflow

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* v1.13.0 release

v1.13.0 release

---

README.md
docs/CONFIGURATION.md
docs/TROUBLESHOOTING.md
examples/kubernetes/static_provisioning/aws_max_attempts.yaml
examples/kubernetes/static_provisioning/caching.yaml
examples/kubernetes/static_provisioning/kms_sse.yaml
examples/kubernetes/static_provisioning/multiple_pods_one_pv.yaml
examples/kubernetes/static_provisioning/non_root.yaml
examples/kubernetes/static_provisioning/pod_level_identity.yaml
examples/kubernetes/static_provisioning/s3_express_specify_az.yaml
examples/kubernetes/static_provisioning/static_provisioning.yaml
examples/kubernetes/static_provisioning/static_provisioning_with_shared_cache.yaml

Create `TROUBLESHOOTING.md` and update examples to mention `volumeHandle` must be unique

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

*Description of changes:* v1.14.0 release

v1.14.0 release

---

CHANGELOG.md
Dockerfile

Bump Mountpoint to v1.16.2 and update CHANGELOG

---

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml

*Issue:*
https://github.com/awslabs/mountpoint-s3-csi-driver/issues/427
Added resource constraints to the init container and parameterized the values using templates.

Init container resource limits

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml

v1.14.1 release

---

README.md

Add `Unstable Releases` section to `README.md`

---

README.md
docs/INSTALL.md

Update documentation regarding minimum supported Kubernetes version

---

cmd/aws-s3-csi-controller/csicontroller/reconciler.go
pkg/driver/node/volumecontext/volume_context.go
pkg/podmounter/mppod/creator.go
pkg/podmounter/mppod/creator_test.go
tests/controller/controller_test.go

Allow configuring Mountpoint Container's resource limits and requests at volume-level

---

cmd/aws-s3-csi-mounter/csimounter/csimounter.go
cmd/aws-s3-csi-mounter/csimounter/csimounter_test.go
pkg/mountpoint/runner/foreground.go
pkg/mountpoint/runner/runner.go

This is part of the effort of consolidating Mountpoint related
functionalities in `github.com/awslabs/aws-s3-csi-driver/pkg/mountpoint`
package.
---

Create `runner.RunInForeground` function in `github.com/awslabs/aws-s3-csi-driver/pkg/mountpoint/runner` package

---

cmd/aws-s3-csi-controller/csicontroller/reconciler.go
tests/controller/controller_test.go

Ensure to not assign new workload to Mountpoint Pod if its annotated with "needs-unmount"

---

pkg/driver/node/credentialprovider/provider_pod.go
tests/e2e-kubernetes/testsuites/credentials.go

Add waiting for policies to be attached during role creation

---

cmd/aws-s3-csi-mounter/csimounter/csimounter.go
pkg/driver/node/mounter/pod_unmounter.go
pkg/podmounter/mppod/creator.go
pkg/podmounter/mppod/creator_test.go
pkg/podmounter/mppod/path.go

Create an `emptyDir` volume in Mountpoint Pod to use as local-cache if enabled

---

tests/e2e-kubernetes/testsuites/pod_sharing.go

Add new Pod sharing test-cases to ensure Mountpoint Pod is not terminated preemptly

---

docs/CONFIGURATION.md
docs/TROUBLESHOOTING.md
examples/kubernetes/static_provisioning/outpost_bucket.yaml

Improves the configuration and troubleshooting docs with information on how to set up an S3 Outposts bucket correctly

Update docs to add more information on using S3 Outposts

---

docs/CONFIGURATION.md

Updates the text in the configuration guide for outposts and static provisioning.

Update docs for Outposts

---

README.md

Add v2 announcement banner to README

---

README.md

Remove mention of "today" in v2 README note

---

examples/kubernetes/static_provisioning/outpost_bucket.yaml

Update wording on outpost_bucket.yaml to mention Outpost aliases

---

CHANGELOG.md
Dockerfile

Bump Mountpoint to v1.19.0

---

charts/aws-mountpoint-s3-csi-driver/templates/mountpoints3podattachments-crd.yaml
docs/LOGGING.md
pkg/api/v2beta/mountpoints3podattachment_types.go

[Rendered](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/60ebe81996e5b503c7d59454dcf224fbd3ff89d9/docs/LOGGING.md)
---

Upgrade logging documentation for v2

---

docs/CONFIGURATION.md
examples/kubernetes/static_provisioning/caching.yaml
pkg/podmounter/mppod/creator.go

*Issue #, if available:* Fixing v2 links
*Description of changes:* Search&Replace `/blob/v2/` -> `/blob/main/`

Fix v2 links

---

docs/HEADROOM_FOR_MPPOD.md
go.mod
go.sum

Bump `golang.org/x/oauth2` to `0.27.0`

---

CHANGELOG.md
Makefile
README.md
charts/aws-mountpoint-s3-csi-driver/Chart.yaml
charts/aws-mountpoint-s3-csi-driver/values.yaml
deploy/kubernetes/overlays/stable/kustomization.yaml
docs/UPGRADING_TO_V2.md

v2.0.0 release

---

tests/e2e-kubernetes/testsuites/util.go

With a recent addition to our testing matrix, we now run our end-to-end tests with 44 clusters in parallel. The tests in those clusters are also run in parallel and this caused some throttling errors in various AWS services especially from the IAM service.
This change tries to make the test suite more resilient by increasing the maximum retry amount from 3 to 5 and also increasing maximum backoff duration from 20s to 2m.
---

Increase max retry attempts and backoff in end-to-end tests

---

CHANGELOG.md
Dockerfile

*Description of changes:* Bump Mountpoint to v1.20.0

Bump Mountpoint to v1.20.0

---

Dockerfile
go.mod
tests/e2e-kubernetes/go.mod

Bump go.mod to the latest Go version
