.github/workflows/e2e-tests.yaml, .github/workflows/release.yaml, tests/e2e-kubernetes/README.md
CI IAM roles are renamed and defined in github variables now
___
=> Use IAM roles from github variables

.github/workflows/release.yaml
* Allow GH actions to cut release, was missing [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
=> Allow GH actions to cut release

.github/workflows/release.yaml, CHANGELOG.md, Makefile, README.md
=> Staging v1.2.0 release

examples/kubernetes/static_provisioning/README.md, examples/kubernetes/static_provisioning/multiple_pods_one_pv.yaml
*Issue #145 
- Added new yaml manifest to deploy a Deployment kind object, that creates a set of pod replicas using same PV to get access to bucket, allowing it to scale up and in your pods.
- Added this description into REAME file
thanks
=> Added new yaml manifest to Deployment kind that can scale pods using same PV

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, deploy/kubernetes/base/node-daemonset.yaml, examples/kubernetes/static_provisioning/static_provisioning.yaml
*Issue #, if available:* #86
*Description of changes:* Add support for Bottlerocket OS. New versions of Bottlerocket are adding SELinux policies and directories to support installing the CSI driver and this PR adds SELinux labels to the containers to work with these changes. The install and node driver containers must run with the `super_t` SELinux user. The Bottlerocket policies are configured such that the installed files will automatically get the correct labels applied, so it turns out there is no relabeling required.
=> Add SELinux options for Bottlerocket

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, pkg/driver/node.go
* Remove duplicated empty node.resources values.
* The Helm chart and Kubernetes manifest are set up to use HOST_PLUGIN_DIR, but the mountpoint-s3-csi-driver utilizes HOST_TOKEN_DIR. Since HOST_PLUGIN_DIR and HOST_TOKEN_DIR serve the same purpose, we are replacing HOST_TOKEN_DIR with HOST_PLUGIN_DIR to standardize the configuration.
Tested in onPrem K8S lab (with IRSA), deployed with [K0S](https://github.com/k0sproject/k0s).
=> Replace HOST_TOKEN_DIR environment variable by HOST_PLUGIN_DIR

Dockerfile
The tools included in the CSI base image are no longer needed after the mount code was refactored. This change reduces the docker image size from 93MB to 33MB.
=> Switch from csi base image to plain base image

.github/workflows/unit-tests.yaml
*Description of changes:* Run unit tests as root as part of the CI. Previously, some tests weren't running because they had an ['is running as root' check](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/8938019603/job/24551349632?pr=193#step:8:78).
=> Run unit tests as root in Github actions

.github/workflows/unit-tests.yaml, .gitignore, .testcoverage.yml, Makefile
*Description of changes:* Introduce coverage tests that are ran during PRs and pushes to main. 
No coverage requirements as of yet.
=> Test coverage in PRs

examples/kubernetes/static_provisioning/static_provisioning.yaml
*Issue #, if available:* #198
This change simply adds a prefix to the main static provisioning example. We did not have an example to share in #198. The prefix doesn't need to already exist.
Tested by deploying the PV and example pod (replacing bucket name), getting a shell in the pod and touching a file named `using-s3-csi-with-prefix-arg.txt`, and checking files are created as expected.
```
❯ aws s3 ls --recursive s3://DOC-EXAMPLE-BUCKET/
2024-05-15 14:16:34         26 some-s3-prefix/Wed May 15 13:16:32 UTC 2024.txt
2024-05-15 14:21:55          0 some-s3-prefix/using-s3-csi-with-prefix-arg.txt
```
=> Add prefix to static_provisioning example

tests/e2e-kubernetes/testsuites/multivolume.go
The e2e test "should concurrently access the single volume from pods on different node" did not include an argument for running the pods on different nodes - there was no difference between it and the test for "should concurrently access the single volume from pods on the same node".
=> Fix a typo in the e2e test suite

charts/aws-mountpoint-s3-csi-driver/values.yaml, docs/install.md
564
Added a default annotation for the SA.
ref.: https://github.com/awslabs/mountpoint-s3-csi-driver/issues/173#issuecomment-2209120237
=> Missing node.serviceAccount.annotations in values.yaml

pkg/system/pts.go, pkg/system/pts_darwin.go, pkg/system/pts_linux.go, pkg/system/pts_test.go
This allows us to build and test our code on macOS for local development. With this change, `make test` works on macOS.
---
=> Move Linux specific code for Pts to `pts_linux.go`

charts/aws-mountpoint-s3-csi-driver/templates/serviceaccount-csi-node.yaml
*Description of changes:* Fixes permission issue where the driver's service role was unable to get service account information
=> Add cluster role to helm service account definition

pkg/driver/mount.go
Until we find the root cause of why reading `/proc/mounts` on newly spawned Karpenter/GPU nodes fails, we're adding retry mechanism to reading `/proc/mounts` as people reported that reading `/proc/mounts` works after retries. See  https://github.com/awslabs/mountpoint-s3-csi-driver/issues/174
This originally contributed by @Shellmode, but since our CI is not properly set up yet, the original PR didn't triggered the CI. This PR is from a branch, and it should properly trigger the CI.
---
=> Add retry to reading `/proc/mounts`

pkg/driver/credential.go, pkg/driver/credential_test.go, pkg/driver/mount.go, pkg/driver/mount_test.go, pkg/driver/node.go, tests/e2e-kubernetes/testsuites/credentials.go
This PR adds the following improvements:
- Ensure we don't log sensitive information from `csi.NodePublishVolumeRequest`
- Disable caching with pod-level credentials
- Ensure to disable all other credential providers except STS provider
- Add a test case to make sure we're not using secrets if pod-level identity is enabled
---
=> Pod-level identity improvements

charts/aws-mountpoint-s3-csi-driver/templates/csidriver.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, deploy/kubernetes/base/csidriver.yaml, docs/CONFIGURATION.md, pkg/driver/credential.go
Enable `podInfoOnMount` when k8s>=1.30
----
Tested with 
```
helm template --kube-version 1.30 --debug charts/aws-mountpoint-s3-csi-driver | python3 -m yq 'select(.kind=="CSIDriver") | .spec | .podInfoOnMount'
true
helm template --kube-version 1.29 --debug charts/aws-mountpoint-s3-csi-driver | python3 -m yq 'select(.kind=="CSIDriver") | .spec | .podInfoOnMount'
null
```
=> Enable `podInfoOnMount` when using k8s>=1.30

tests/e2e-kubernetes/testsuites/credentials.go
Remove 'eks' prefix requirement for OIDC detection for E2E tests.
=> For OIDC credentials, allow providers starting with 'oidc.'

docs/CONFIGURATION.md, examples/kubernetes/static_provisioning/README.md, examples/kubernetes/static_provisioning/aws_max_attempts.yaml, examples/kubernetes/static_provisioning/caching.yaml, examples/kubernetes/static_provisioning/kms_sse.yaml, examples/kubernetes/static_provisioning/multiple_buckets_one_pod.yaml, examples/kubernetes/static_provisioning/multiple_pods_one_pv.yaml, examples/kubernetes/static_provisioning/non_root.yaml, examples/kubernetes/static_provisioning/pod_level_identity.yaml, examples/kubernetes/static_provisioning/s3_express_specify_az.yaml, examples/kubernetes/static_provisioning/static_provisioning.yaml
The Driver only supports Static Provisioning as of today, and in order to configure it correctly, one needs to ensure there is no `storageClassName` set (it should be `""`) and also there is a one-to-one mapping between PVC and PV using `claimRef`. This PR clarifies this requirement and updates example manifests to specify one-to-one mapping between PVC and PV. See a recent issue regarding this: https://github.com/awslabs/mountpoint-s3-csi-driver/issues/249
--- 
=> Mention one-to-one mapping of PVCs and PVs in the docs and examples

charts/aws-mountpoint-s3-csi-driver/templates/csidriver.yaml
Current version compare `(semverCompare ">=1.30" .Capabilities.KubeVersion.Version)` does not work with EKS versions (e.g., `v1.30.4-eks-a737599`) and requires customers to set `node.podInfoOnMountCompat.enable=true` even though they're on 1.30+ clusters. 
The test script:
```bash
#!/usr/bin/env bash
echo "Testing versions >=1.30:"
for version in "v1.30.0" "v1.31.2" "v1.30.4-eks-a737599" "v1.30.1+k3s1" "v1.30.4+k0s"; do
helm template --debug aws-mountpoint-s3-csi-driver \
--namespace kube-system \
--kube-version "$version" \
./charts/aws-mountpoint-s3-csi-driver 2>&1 | grep -q podInfoOnMount && echo -e "\t$version - OK" || echo -e "\t$version - FAIL"
done
echo "Testing versions <1.30:"
for version in "v1.29.0" "v1.27.2" "v1.29.1-eks-61c0bbb" "v1.29.1+k3s1"; do
helm template --debug …
```
=> Fix version compare in Helm chart for `podInfoOnMount`

pkg/driver/node/node.go, pkg/driver/node/node_test.go
- Cleanup tokens after unmounting Mountpoint. Mountpoint might still need to perform some S3 calls during shutdown and cleaning the token before unmount might cause those operations to fail.
- Add test to ensure tokens are cleaned up on `NodeUnpublishVolume`. There was a typo in `if err != nil {` check, which was skipping the cleanup if `err` was `nil`, it's been fixed as well.
---
=> Properly clean service account tokens in `NodeUnpublishVolume`

docs/CONFIGURATION.md
=> Add cross-account bucket access via bucket policies example to docs

tests/e2e-kubernetes/e2e_test.go, tests/e2e-kubernetes/s3client/client.go, tests/e2e-kubernetes/testdriver.go
This PR moves S3 client used in tests to its own package for making it reusable. It also changes the logic for generating testing bucket names. Previously we were using cluster name as prefix, and also we had a logic to truncate bucket name to make space for `--azid--x-s3` suffix. That was causing unique hash in the bucket name to be truncated and different clusters to use the same name, and it was causing spurious failures such as https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/11835794931/job/32979499659#step:10:2599.
---
=> Move testing S3 client to its own package

tests/e2e-kubernetes/e2e_test.go, tests/e2e-kubernetes/testsuites/cache.go, tests/e2e-kubernetes/testsuites/util.go
=> Add end-to-end tests for local cache

Makefile, cmd/aws-s3-csi-mounter/csimounter/csimounter.go, cmd/aws-s3-csi-mounter/csimounter/csimounter_test.go, cmd/aws-s3-csi-mounter/main.go, go.mod, pkg/podmounter/mountoptions/mount_options.go, pkg/podmounter/mountoptions/mount_options_test.go, pkg/util/socket.go, pkg/util/socket_test.go, pkg/util/testutil/assert/assert.go
This is part of https://github.com/awslabs/mountpoint-s3-csi-driver/issues/279.
This new component, `aws-s3-csi-mounter`, will be the entry point for the container running Mountpoint. It will be responsible for receiving mount options and FUSE file descriptor and spawning Mountpoint process until completion.
---
=> Add `aws-s3-csi-mounter` component

tests/e2e-kubernetes/s3client/client.go, tests/e2e-kubernetes/testsuites/cache.go
[Mountpoint v1.11.0](https://github.com/awslabs/mountpoint-s3/blob/main/mountpoint-s3/CHANGELOG.md#v1110-november-21-2024) added support for caching objects to S3 Express bucket. This PR adds some end-to-end tests to make sure it works with the CSI Driver without any problem.
---
=> Add tests for Express cache

tests/e2e-kubernetes/e2e_test.go, tests/e2e-kubernetes/scripts/run.sh, tests/e2e-kubernetes/testdriver.go, tests/e2e-kubernetes/testsuites/credentials.go
*Issue:*
This PR addresses Credentials test failures in clusters without IMDS access. 
*Description of Changes:*
- Add a new flag `imds-available` to indicate if IMDS is available.
- Configure the STS region through the `bucket-region` flag and pass the region explicitly to the tests.
- Add a test case to verify automatic STS region detection when the `imds-available` is set to true.
=> Update E2E Tests to Support Explicit STS Region Configuration 

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml
Currently, the `imagePullPolicy` was hardcoded to `IfNotPresent` for `s3-plugin` . This PR updates the Helm chart template to make the` imagePullPolicy` for the `s3-plugin` container configurable via Helm values.
=> Make `s3-plugin` container's `imagePullPolicy` configurable

tests/e2e-kubernetes/scripts/eksctl.sh
We were missing "NotFound" checks in our CI while trying to remove security groups, and it was causing this operation to retry until max retry time which is 10 minutes. This was resulting temporary credentials issued for CI to expire, and the CI run to fail. See https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/12392057877/job/34648273564 for example. We might still need to increase duration of temporary credentials from 1 hour to a longer duration if our CI keeps taking longer, but for now this should address the issue, hopefully.
---
=> Stop retrying to delete security group if we got "NotFound" error

.github/workflows/e2e-tests.yaml, tests/e2e-kubernetes/scripts/run.sh
Currently, we use stable version of kubectl (v1.32 as of today), and that might cause some problems as kubectl [emits a warning](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/12561703668/job/35021134764#step:11:4567): 
> WARNING: version difference between client (1.32) and server (1.29) exceeds the supported minor version skew of +/-1
---
=> Use kubectl matching with cluster's version

.github/workflows/e2e-test-push.yaml, .github/workflows/e2e-test-trusted.yaml, .github/workflows/e2e-test-untrusted.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/release.yaml, Makefile
Use github environments to separate the different security boundaries we have: an 'untrusted' account for third party forks, and a 'trusted' account for direct pushes and merges. The 'trusted' account is then used as a source for releases, and it will only run code that's already merged into the main repository. 
Testing E2E: https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/12653780902
Testing release: https://github.com/muddyfish/mountpoint-s3-csi-driver/actions/runs/12411681334
**Before Merging**: Need to create GitHub environments on main repository.
=> Update CI to use Github Environments

.github/workflows/e2e-tests.yaml
*Description of changes:* As part of testing PRs from a fork (https://github.com/muddyfish/mountpoint-s3-csi-driver/actions/runs/12668838554/job/35326379030#step:5:1), the steps timed out due to the aws credentials expiring. This is because the aws action defaults to a 1 hour validity, and our tests take a long time. This PR increases the validity requested to two hours.
=> Set assume role timeout to 2 hours for e2e tests

.github/workflows/e2e-test-trusted.yaml, .github/workflows/e2e-test-untrusted.yaml, .github/workflows/e2e-tests.yaml
Runs the trusted e2e tests for PRs from the main repo, and only runs the untrusted e2e tests for PRs from forks
=> Run e2e tests as trusted or not depending on if they're from a fork

.github/workflows/e2e-test-trusted.yaml, .github/workflows/e2e-test-untrusted.yaml
*Description of changes:* Adds an 'approval gate' step, which only waits to be approved. In the main MP CSI Driver repo, added an environment 'approval-gate' which needs an approval to run. Adding the 'needs' delays the rest of the tests from running until an admin approves, and means we can remove the approver from the 'untrusted' environment after merging
Closes https://github.com/awslabs/mountpoint-s3-csi-driver/pull/338, as previous PR was on a 'workflow' branch, and this is not required and increases the time taken to merge in.
=> Add approval gate environment

pkg/driver/node/mounter/credential_provider.go, pkg/driver/node/node.go, pkg/driver/node/volumecontext/volume_context.go
Splitted out of https://github.com/awslabs/mountpoint-s3-csi-driver/pull/328. 
This might not make sense since it's moved out of its original context, but the original motivation was that these constants was spread out to different packages and that was causing circular dependencies.
For example, if you need to use `VolumeCtxBucketName` in `pkg/driver/node/mounter` package, you'd need to import `pkg/driver/node` package which would cause a circular dependency as `pkg/driver/node` imports `pkg/driver/node/mounter`. In situations like that, it's best to extract common things into a leaf package that doesn't import anything, which is what this PR does with `pkg/driver/node/volumecontext` package.
It also makes finding these volume context keys easier by placing them into a singular place. …
=> Add `volumecontext` package for accessing volume context from CSI

.github/workflows/e2e-test-untrusted.yaml
*Description of changes:* A typo whilst merging conflicts meant that the untrusted e2e workflow never ran. This fixes it
=> Fix typos in e2e untrusted workflow

pkg/podmounter/mppod/path.go, pkg/podmounter/mppod/path_test.go
This is to make this API nicer to use by having a similar semantics to `filepath.Join`
---
=> Make path argument variadic in `PathOnHost` and `PathInsideMountpointPod`

pkg/podmounter/mountoptions/mount_options.go
`net.{Listen, Dial}` functions does not accept context argument, but only `{ListenContext, DialContext}` counterparts do. But even those functions does not respect to context's deadline, so we need to call `SetDeadline` with passed context's deadline explicitly to ensure context's deadline is respected.
---
=> Make sure `mountoptions.{Send, Recv}` respects `ctx`'s deadline

.github/matrix.yaml, .github/workflows/build_matrix.yaml, .github/workflows/e2e-tests.yaml
*Description of changes:* Adds a new workflow which generates a reusable matrix of K8s versions that we can use in other workflows (e2e tests)
=> Add reusable matrix creation workflow

tests/e2e-kubernetes/testsuites/cache.go, tests/e2e-kubernetes/testsuites/credentials.go, tests/e2e-kubernetes/testsuites/mountoptions.go, tests/e2e-kubernetes/testsuites/util.go
=> Add non-root end-to-end test cases to credentials test suite

.github/matrix.yaml, tests/e2e-kubernetes/scripts/run.sh
*Description of changes:* EKS now supports v1.32. 
- Added support for Kubernetes v1.32.1 to CI
- Upgraded `eksctl` to v0.202.0 as 0.191.0 does not support v1.32
- https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html#platform-versions-1.32
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.32.md
=> Add Kubernetes v1.32.1 to CI

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml
Resolves #348 
This PR will move the hardcoded tolerations from the DaemonSet template to the values, ~~I just used the [aws-fsx-csi-driver](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/charts/aws-fsx-csi-driver/templates/node-daemonset.yaml#L39-L45) helm chart as inspiration. As this is probably the simplest solution, it may lead to unexpected changes if someone already has `tolerations` set.~~
I have added a new value: `node.defaultTolerations` and put it in the `else` condition in `tolerateAllTaints`.
---
=> Allow overriding of hardcoded DaemonSet tolerations

pkg/driver/node/node.go, pkg/util/kubelet.go
This function will be reused in upcoming `PodMounter` and `util` package seems like a better place.
---
=> Move fuction to get kubelet path into `util` package

cmd/aws-s3-csi-mounter/csimounter/csimounter_test.go, pkg/driver/node/mounter/mountertest/mounter.go
These utils will be reused in upcoming `PodMounter` therefore moved into a separate package to make it reusable.
---
=> Create `mountertest` package for mount test utils

Dockerfile, Dockerfile.local, Makefile
With containerization, we will run Mountpoint inside our container and we will need `libfuse` and `glibc` for Mountpoint to run - which CSI base image provides.
---
=> Update `Dockerfile`s to use CSI minimal image and add new components

cmd/aws-s3-csi-controller/main.go
To have consistency with other options and to ensure we don't hard-code Mountpoint namespace, get it from `MOUNTPOINT_NAMESPACE` env by default.
---
=> Get default Mountpoint namespace from env in CSI Controller

.github/matrix.yaml
*Issue #, if available:* We previously removed v1.32 Ubuntu2204 from this PR (https://github.com/awslabs/mountpoint-s3-csi-driver/pull/357) because at that time 1.32 Ubuntu2204 AMI image was not available in AWS Parameter Store. 
*Description of changes:* Add v1.32 Ubuntu2204 into CI matrix as these images are now available
=> Add v1.32 Ubuntu2204 into CI matrix

cmd/aws-s3-csi-mounter/csimounter/csimounter.go, cmd/aws-s3-csi-mounter/csimounter/csimounter_test.go, cmd/aws-s3-csi-mounter/main.go, pkg/driver/node/mounter/mounter.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_darwin.go, pkg/driver/node/mounter/pod_mounter_linux.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/driver/node/mounter/systemd_mounter.go, pkg/podmounter/mountoptions/mount_options.go, pkg/podmounter/mountoptions/mount_options_test.go, pkg/podmounter/mppod/path.go, pkg/util/testutil/chdir.go
Part of https://github.com/awslabs/mountpoint-s3-csi-driver/issues/279. This `PodMounter` is not in use at the moment, only tests are running for it. I'll do a follow-up PR to add Kubernetes manifests and enabling this `PodMounter` via Helm flag.
Best reviewed on commit-by-commit.
---
=> Add `PodMounter`

pkg/driver/node/mounter/fake_mounter.go, pkg/driver/node/mounter/mocks/mock_mount.go, pkg/driver/node/mounter/mounter.go, pkg/driver/node/mounter/systemd_mounter.go, pkg/driver/node/mounter/systemd_mounter_test.go, pkg/driver/node/node.go, pkg/driver/node/node_test.go
`SystemdMounter` was creating a background context in the constructor and using it when a context needed – which is not a good practice as main reason for contexts are cancellation and timeouts but creating a background context kills that benefit. Now, `mounter.Unmount` accepts context as a first argument.
---
=> Add context argument to `mounter.Unmount` method

charts/aws-mountpoint-s3-csi-driver/templates/controller.yaml, charts/aws-mountpoint-s3-csi-driver/templates/mount-s3-namespace.yaml, charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, charts/aws-mountpoint-s3-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-mountpoint-s3-csi-driver/templates/serviceaccount-csi-node.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml
This PR adds Kubernetes manifests changes to the Helm chart behind `experimental.podMounter` feature-flag. 
Unless you pass `experimental.podMounter`, it won't change anything semantically:
```bash
$ helm template ./charts/aws-mountpoint-s3-csi-driver > main-rendered
$ helm template aws-mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver > v1.12.0-rendered
```
`diff v1.12.0-rendered main-rendered`:
```diff
44d43
< # Source: aws-mountpoint-s3-csi-driver/templates/node.yaml
91a91,92
>
>       # This `install-mountpoint` is only needed with `SystemdMounter` and not with `PodMounter`.
111a113
>
```
and to compare when you enable `experimental.podMounter`:
```bash
$ helm template ./charts/aws-mountpoint-s3-csi-driver --set experimental.podMounter=true > pod-mounter-rendered
```
<details> …
=> Add `PodMounter` manifests behind `experimental.podMounter` Helm feature-flag

pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_test.go
In a recent refactor, I accidentally used volume id for Mountpoint Pod's name. The unit tests were passing because they were both the same, but the controller uses [PV's name to generate](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/cmd/aws-s3-csi-controller/csicontroller/reconciler.go#L167) Mountpoint Pod name. This would have been caught with the end-to-end tests probably, but since we don't run end-to-end tests in our CI for `PodMounter` yet, it was missed. Plan to enable end-to-end tests after https://github.com/awslabs/mountpoint-s3-csi-driver/pull/372.
---
=> Use PersistentVolume's name for Mountpoint Pod name in `PodMounter`

pkg/driver/node/credentialprovider/provider_test.go, pkg/driver/node/envprovider/provider_test.go, pkg/util/testutil/env.go
Fixes https://github.com/awslabs/mountpoint-s3-csi-driver/issues/359. I introduced some buggy tests that was assuming a clean environment, and was failing if that was not the case. As shared by @renanmagagnin, the tests were failing if you have `AWS_REGION` environment variable set in your terminal. 
I detected these test cases by running with `AWS_REGION="fail" AWS_DEFAULT_REGION="fail" make test` and updated them to call `testutil.CleanRegionEnv` to have a clean environment.
---
=> Ensure we clear AWS Region environment variables in our tests

pkg/driver/driver.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/podmounter/mppod/watcher/watcher.go, pkg/podmounter/mppod/watcher/watcher_test.go
This PR introduces `mppod/watcher` package for properly watching Mountpoint Pods using Kubernetes [informers](https://pkg.go.dev/k8s.io/client-go/informers). Informers does caching and handles transient errors from the control plane.
Also fixes the potential race conditions mentioned in https://github.com/awslabs/mountpoint-s3-csi-driver/pull/368/files#r1950851325. The `Wait` method set up a watcher first, and then checks if the Pod already seen by doing a `Get` and if not, it just listens events from the watcher.
---
=> Create `mppod/watcher` package for watching Mountpoint Pods

.github/workflows/e2e-tests.yaml, tests/e2e-kubernetes/scripts/helm.sh, tests/e2e-kubernetes/scripts/run.sh
This PR updates CI configuration to run `PodMounter` tests after `SystemdMounter` tests by re-using the same cluster. It cleans the cluster by uninstalling the Helm chart, [deleting all test namespaces and resources](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/tests/e2e-kubernetes/scripts/run.sh#L163-L176).
---
=> Run tests with both `SystemdMounter` and `PodMounter` in CI

Makefile, tests/e2e-kubernetes/go.mod, tests/e2e-kubernetes/go.sum, tests/e2e-kubernetes/scripts/run.sh, tests/e2e-kubernetes/testsuites/credentials.go, tests/e2e-kubernetes/testsuites/multivolume.go, tests/e2e-kubernetes/testsuites/util.go
[Recent change](https://github.com/awslabs/mountpoint-s3-csi-driver/pull/381) to add `PodMounter` tests to our CI made our slow end-to-end tests even slower, and it started timing out. This PR implements some improvements to speed up end-to-end tests:
- [Run end-to-end tests in parallel using ginkgo](https://github.com/awslabs/mountpoint-s3-csi-driver/commit/a1291d20a33e01e4f69328fff238090e7800f63d) – Most end-to-end tests can be run in parallel as they create isolated namespaces, pods, and volumes. Once exception is credential tests – which need to change some cluster-level resources – and they already [declared to run as serial](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/tests/e2e-kubernetes/testsuites/credentials.go#L266-L270). So, making tests run in parallel using …
=> Speed up end-to-end tests

tests/controller/suite_test.go, tests/e2e-kubernetes/testsuites/credentials.go, tests/e2e-kubernetes/testsuites/performance.go, tests/e2e-kubernetes/testsuites/util.go
*Description of changes:* Removes hard-coded `aws` partition, and uses sts getCallerIdentity to retrieve an ARN which can be used to extract the current partition. Additionally, replaces busybox from dockerhub with busybox from ecr public.
=> Support alternative partitions in e2e tests

pkg/podmounter/mppod/creator.go, pkg/podmounter/mppod/creator_test.go, tests/controller/controller_test.go
=> Update Mountpoint Pod spec to tolerate all taints

tests/e2e-kubernetes/testsuites/performance.go
*Description of changes:* Fixes https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/13467948148/job/37637382907
Tested with
```
rm ~/china-logs.log && AWS_PROFILE=china KUBE_TEST_REPO_LIST=./kube_image_configs.yaml GOPROXY=direct KUBECONFIG=~/.kube/config go test -ginkgo.vv -timeout 120m --bucket-region=cn-north-1 --imds-available true --performance=true > ~/china-logs.log
```
```
Ran 31 of 72 Specs in 1968.885 seconds
SUCCESS! -- 31 Passed | 0 Failed | 0 Pending | 41 Skipped
```
=> Fix performance tests failing on missing `apt`

tests/e2e-kubernetes/scripts/eksctl.sh, tests/e2e-kubernetes/scripts/kops.sh
This PR updates our testing script for `eksctl` and `kOps` clusters to:
1. Not delete clusters after running tests on them if they're not older than 3 days
2. Re-use existing cluster if the existing cluster's spec matches with the expected one
Hopefully this should speed up the CI time greatly.
---
=> Re-use testing clusters up to 3 days in CI

charts/aws-mountpoint-s3-csi-driver/templates/controller.yaml, charts/aws-mountpoint-s3-csi-driver/templates/mount-s3-priority.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, cmd/aws-s3-csi-controller/main.go, pkg/podmounter/mppod/creator.go, pkg/podmounter/mppod/creator_test.go, tests/controller/controller_test.go, tests/controller/suite_test.go
=> Set a default `priorityClassName` to Mountpoint Pods and allow customizing

tests/e2e-kubernetes/scripts/eksctl-patch.json, tests/e2e-kubernetes/scripts/kops-patch.yaml
*Description of changes:* Add a managed policy to enable AWS Systems Manager service core functionality: 
https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonSSMManagedInstanceCore.html
___
=> Allow access to AWS System Manager from CI nodes

tests/e2e-kubernetes/s3client/client.go, tests/e2e-kubernetes/testsuites/cache.go
Recent changes to the CI (https://github.com/awslabs/mountpoint-s3-csi-driver/pull/390) and tests (https://github.com/awslabs/mountpoint-s3-csi-driver/pull/384) caused most tests to run in parallel at the same time. This started [causing](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/13576832181/job/37954945757#step:11:1522) some throttling errors on `CreateBucket`/`DeleteBucket` operations on S3 Express buckets. This PR increases retries and backoffs for S3 operations and also changes Express cache tests to run in serial to reduce number of parallel requests.
---
=> Increase retries and backoffs for S3 operations & run Express cache tests in serial 

pkg/driver/driver.go, pkg/driver/node/envprovider/provider.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/driver/node/mounter/systemd_mounter_test.go, pkg/podmounter/mppod/mppod.go, pkg/podmounter/mppod/watcher/watcher.go, pkg/podmounter/mppod/watcher/watcher_test.go, pkg/system/systemd.go, pkg/system/systemd_test.go, pkg/util/testutil/assert/assert.go
Run newly added `modernize` analyzer from `gopls` v0.18, namely, `go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...`, to use modern Go features.
---
=> Run `modernize` analyzer

pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_darwin.go, pkg/driver/node/mounter/pod_mounter_linux.go, pkg/driver/node/mounter/systemd_mounter.go
Checking for corrupted mounts with kubernetes/mount-utils package has an issue with networked filesystems, especially ones based on FUSE. Namely, a check based on os.Stat() often returns results cached by the OS kernel, and thus return a valid result even if the underlying filesystem is not responsive anymore, because its userspace part hang.
There are at least two approaches to fix it:
1. Use a more powerful `statx` syscall on linux with a AT_STATX_FORCE_SYNC flag set. That explicitly asks for not getting results from cache and is more likely to detect a corrupted mount.
2. Use ReadDir. That one I simply verified empirically to work better than os.Stat. It tends to not serve results from cache, and has an additional perk than it trips if the mount point is not a directory.
<strike>
This …
=> node/mounter: add a more robust check for corrupted mounts

Makefile
We enabled provenance on our Docker images recently via https://github.com/awslabs/mountpoint-s3-csi-driver/pull/398, but then we realized our current release procedure doesn't handle it properly. We're disabling it back until we update our release procedure to properly support it.
---
=> Temporarily disable provenance on Docker image

.github/workflows/e2e-tests.yaml
*Description of changes:* The changes in the [previous PR](https://github.com/awslabs/mountpoint-s3-csi-driver/pull/410) correctly tagged the architecture specific images but failed when being executed more than once. This change fixes this by suppressing `ImageAlreadyExistsException`.
Tested the E2E tests workflow in my fork.
=> Ensure idempotence in post_test step of e2e-tests

tests/e2e-kubernetes/scripts/eksctl-patch.json, tests/e2e-kubernetes/scripts/eksctl.sh
*Description of changes:* Add EKS CW Observability addon to e2e clusters in order for better troubleshooting E2E test failures
- Pre-create log groups with 30 day retention before cluster creation
*Manual Testing*: Manually verified that logs are now enabled and created with 30 day retention in personal clusters
=> Add EKS CW Observability addon to e2e clusters

examples/kubernetes/static_provisioning/aws_max_attempts.yaml, examples/kubernetes/static_provisioning/caching.yaml, examples/kubernetes/static_provisioning/kms_sse.yaml, examples/kubernetes/static_provisioning/multiple_buckets_one_pod.yaml, examples/kubernetes/static_provisioning/multiple_pods_one_pv.yaml, examples/kubernetes/static_provisioning/non_root.yaml, examples/kubernetes/static_provisioning/s3_express_specify_az.yaml, examples/kubernetes/static_provisioning/static_provisioning.yaml, examples/kubernetes/static_provisioning/static_provisioning_with_shared_cache.yaml
*Description of changes:* Current examples are failing to be deployed with error: `docker.io/library/centos:latest: not found`
[CentOS looks like to be deprecated](https://hub.docker.com/_/centos). Replace it with `ubuntu` image. 
=> Replace centos with ubuntu in examples

tests/e2e-kubernetes/scripts/eksctl.sh
The CI [seems to be broken](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/14110780306/job/39538720856?pr=421) because for `s3-csi-cluster-eksctl-amazonlinux2-x86` cluster, the EKS cluster does not exist but the CloudFormation stack exists and stuck in `ROLLBACK_COMPLETE` status. Current CI script doesn't try to remove the CF stack if the cluster does not exist, this PR updates `eksctl_delete_cluster` to try to delete the CF stack even if the cluster does not exist.
---
=> Ensure CloudFormation stacks are deleted in cluster clean up

pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_linux.go, pkg/driver/node/mounter/pod_mounter_test.go, tests/e2e-kubernetes/e2e_test.go, tests/e2e-kubernetes/testsuites/accessmode.go, tests/e2e-kubernetes/testsuites/util.go
*Description of changes:* Currently, PodMounter fails to work with `ReadOnlyMany` access mode with error:
```
Error: Mount options: --read-only are ignored with FUSE fd mount point.Mount options should be passed while performing `mount` syscall in the caller process.
```
Fix: Remove `--read-only` flag when it is set
Also, added e2e tests for ReadOnlyMany case to validate that the fix worked.
=> PodMounter: Fix ReadOnlyMany access mode

tests/e2e-kubernetes/scripts/eksctl-patch.json
This is to debug some transient errors such as https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/14379730344/job/40320438436#step:11:4427.
---
=> Enable control plane CloudWatch logging for testing EKS clusters

.gitignore, Dockerfile, Dockerfile.local, Makefile
This PR uses `go-licenses save` to generate licenses, copyright notices and source codes (depending on the license type) and stores them in the container image.
<details>
<summary>`docker export .. | tar t | rg -i LICENSE`</summary>
```
LICENSES/
LICENSES/github.com/
LICENSES/github.com/aws/
LICENSES/github.com/aws/aws-sdk-go-v2/
LICENSES/github.com/aws/aws-sdk-go-v2/LICENSE.txt
LICENSES/github.com/aws/aws-sdk-go-v2/NOTICE.txt
LICENSES/github.com/aws/aws-sdk-go-v2/config/
LICENSES/github.com/aws/aws-sdk-go-v2/config/LICENSE.txt
LICENSES/github.com/aws/aws-sdk-go-v2/credentials/
LICENSES/github.com/aws/aws-sdk-go-v2/credentials/LICENSE.txt
LICENSES/github.com/aws/aws-sdk-go-v2/feature/
LICENSES/github.com/aws/aws-sdk-go-v2/feature/ec2/ …
```
=> Store licenses of Go dependencies in the container image

pkg/driver/driver.go, pkg/driver/node/mounter/mounter.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/driver/node/mounter/systemd_mounter.go, pkg/driver/node/mounter/systemd_mounter_test.go, pkg/mountpoint/mounter/fd.go, pkg/mountpoint/mounter/mount.go, pkg/mountpoint/mounter/mount_darwin.go, pkg/mountpoint/mounter/mount_linux.go
This is part of the effort of consolidating Mountpoint related
functionalities in `github.com/awslabs/aws-s3-csi-driver/pkg/mountpoint`
package.
---
=> Move `mount`, `unmount` and `isMountPoint` functionalities to `github.com/awslabs/aws-s3-csi-driver/pkg/mountpoint/mounter`

pkg/driver/node/mounter/pod_unmounter.go
This causes some error logs to be emitted if there are no S3 volumes in-use currently, this change prevents that.
---
=> Don't emit an error log if source mount dir does not exists in `CleanupDanglingMounts`

Dockerfile, Dockerfile.local
=> Use `public.ecr.aws/eks-distro-build-tooling/golang:1.24` for building Go binaries

.github/workflows/e2e-tests.yaml, tests/e2e-kubernetes/scripts/eksctl-patch.json
These changes correct the setup of test cluster to avoid skipping E2E tests related to Pod Sharing and EKS Pod Identity.
=> Install EKS Pod Identity Agent and include MOUNTER_KIND

cmd/aws-s3-csi-controller/csicontroller/reconciler.go, pkg/podmounter/mppod/creator.go, tests/controller/controller_test.go
=> Ensure to not assign new workload to Mountpoint Pod if its created with a different CSI Driver version or annotated with "no-new-workload"

.github/workflows/controller-tests.yaml, .github/workflows/e2e-tests.yaml
With recent additions to both end-to-end and controller tests, the overall CI time greatly increased. Now we split them into two independent GitHub workflows to allow running in parallel without waiting each other.
---
=> Split end-to-end tests and controller tests into two GitHub workflows

pkg/driver/node/mounter/mppod_lock.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/driver/node/mounter/pod_unmounter.go, pkg/driver/node/mounter/pod_unmounter_test.go
*Description of changes:* Change source mountpoint name to be MP Pod Name instead of UID. UID was previously used because we didn't make get MP Pod call during credential refresh. This is no longer needed as we now always get MP Pod Spec. 
=> Change source mountpoint name to be MP Pod Name instead of UID

pkg/driver/node/credentialprovider/provider.go, pkg/driver/node/credentialprovider/provider_driver.go, pkg/driver/node/credentialprovider/provider_pod.go, pkg/driver/node/credentialprovider/provider_test.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_mounter_test.go, pkg/driver/node/mounter/systemd_mounter.go, pkg/driver/node/mounter/systemd_mounter_test.go, pkg/driver/node/node.go
*Description of changes:* We are not properly refreshing credentials in PodMounter after PodSharing PR.
- Added `MountpointPodID` to credential context
- Renamed `PodID` to  `WorkloadPodID` in credential context
- Use that as Pod ID if it's not empty string
- Validated manually that credentials are now refreshed correctly
=> Use MountpointPodID in credential context

charts/aws-mountpoint-s3-csi-driver/templates/csidriver.yaml, pkg/driver/node/credentialprovider/provider_pod.go, pkg/driver/node/credentialprovider/provider_test.go, tests/e2e-kubernetes/testsuites/credentials.go
*Description of changes:* With this change, we will support the configuration of pod level credentials with EKS Pod Identity. In EKS clusters, this is an alternative to IRSA with an easier configuration process.
*Key Changes:*
- Credential Provider
- In `provider_pod.go` the precedence is given to IRSA credentials. If they are not configured, then EKS Pod Identity credentials are forwarded to the Mountpoint process instead.
- Added unit tests
- Testing
- Added E2E tests covering EKS Pod Identity setup scenarios with IAM roles of varying levels of S3 access
- Added one pod level IRSA E2E test to make sure driver level EKS Pod Identity is not used instead
- Added E2E tests covering setup scenario of IRSA and EKS Pod Identity
- Manual testing performed on personal EKS cluster
By submitting …
=> EKS Pod Identity support for pod level credentials

tests/e2e-kubernetes/testsuites/mountoptions.go
=> Ensure to keep track of created resources in end-to-end tests to properly clean them

tests/e2e-kubernetes/scripts/eksctl.sh, tests/e2e-kubernetes/scripts/run.sh
*Description of changes:* Add read only cluster access to ReadOnly IAM Role to be able to view K8s resources in E2E test clusters.
=> Add read only cluster access to ReadOnly IAM Role

pkg/driver/node/mounter/pod_mounter.go, pkg/mountpoint/mounter/mount.go
Our current check to decide whether given path is a Mountpoint mount does not properly handle bind mounts - which is something we create for Pod sharing. The `IsMountPoint` method from `mount-utils` package properly handles bind mounts as well, and reports any issues correctly. Prior to this change, the CSI Driver was falsely thinking bind mounts are healthy even though they were not.
---
=> Also check `mount-utils`'s `IsMountPoint` in `CheckMountpoint`

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, pkg/driver/node/credentialprovider/provider_pod.go, pkg/driver/node/credentialprovider/provider_test.go, tests/e2e-kubernetes/testsuites/credentials.go
*Description of changes:* In the previous PR (https://github.com/awslabs/mountpoint-s3-csi-driver/pull/458), the default value of the URI was assumed.
=> New driver configuration flag: EKS Pod Identity Agent Credentials URI

charts/aws-mountpoint-s3-csi-driver/templates/node.yaml, cmd/aws-s3-csi-mounter/csimounter/csimounter.go, cmd/aws-s3-csi-mounter/main.go, deploy/kubernetes/base/node-daemonset.yaml, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_unmounter.go, pkg/driver/node/mounter/systemd_mounter.go, pkg/mountpoint/mounter/mount.go
- [Do not mount plugin-dir in CSI Driver container](https://github.com/awslabs/mountpoint-s3-csi-driver/commit/8af73383d96162b8ed6e64d4be1e7c5e71c8ec0b) 
The plugin directory (`/var/lib/kubelet/plugins/s3.csi.aws.com/` by default) was mounted in the CSI Driver container at `/csi`.
However, the kubelet directory (`/var/lib/kubelet` by default) is also mounted in the CSI Driver at `/var/lib/kubelet` which already includes the plugin dir.
This was okay so far, but with Pod sharing we started mounting Mountpoint instances in the plugin dir, and also bind mounts from the kubelet dir for the workloads.
This was causing Mountpoint mounts to have references to themselves in both the plugin dir and the kubelet dir, and due that when we try to unmount them,
we were getting "resource is busy" …
=> Improvements on Mountpoint Pod cleanup with Pod sharing

pkg/driver/node/mounter/pod_unmounter.go
`PodUnmounter` is idempotent and might be called multiple times for the same operation due to way it works, up to this PR we were logging stuff in each invocation which was a bit noisy. Now, we only log if we really performed some operations.
---
=> Improve logging in `PodUnmounter`

cmd/aws-s3-csi-mounter/csimounter/csimounter_test.go, pkg/mountpoint/runner/foreground.go
This should fix the flaky unit test https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/15275854246/job/42961924795?pr=483#step:8:122. 
Verified by running `go test ./cmd/aws-s3-csi-mounter/... -count 10000`. Previously, it was failing multiple times even with 1000 runs.
---
=> Ensure to close FUSE file descriptor after Mountpoint is terminated

pkg/driver/node/credentialprovider/provider.go, pkg/driver/node/credentialprovider/provider_driver.go, pkg/driver/node/credentialprovider/provider_pod.go, pkg/driver/node/credentialprovider/provider_test.go, pkg/driver/node/mounter/pod_mounter.go, pkg/driver/node/mounter/pod_unmounter.go, pkg/driver/node/mounter/systemd_mounter.go
*Description of changes:* During cleanup we currently do not remove IRSA and EKS Pod Identity token files for driver-level credentials.
- Add `MountKind` to `CleanupContext` struct
- If `MountKind` is PodMounter then cleanup IRSA and EKS Pod Identity token files
Manually validated cleanup in personal cluster.
=> Cleanup driver-level token files for PodMounter

cmd/aws-s3-csi-controller/csicontroller/reconciler.go, pkg/driver/node/mounter/pod_mounter.go
This PR changes error messages to include helpful notes, and also sets explicit timeouts for some waiting operations to not wait until the context cancellation in `PodMounter.Mount`. Kubernetes retries failures from `NodePublishVolume`, so it's better to not wait for the whole context duration and error it early and let Kubernetes retry. 
Follow-up for https://github.com/awslabs/mountpoint-s3-csi-driver/pull/487.
For example, if one uses a non-existent PVC as local-cache in a Mountpoint Pod:
```bash
$ kubectl describe pods workload
...
Events:
Type     Reason       Age                From               Message
----     ------       ----               ----               -------
Warning  FailedMount  17s (x4 over 66s)  kubelet            MountVolume.SetUp failed for volume "s3-pv" : rpc …
```
=> Improve error messages in `PodMounter`

tests/e2e-kubernetes/scripts/eksctl-patch.json, tests/e2e-kubernetes/testsuites/cache.go
This is done using the EBS CSI Driver with dynamic provisioning.
Follow-up for https://github.com/awslabs/mountpoint-s3-csi-driver/pull/487.
---
=> Add end-to-end tests using EBS volumes as local-cache in Mountpoint Pod

pkg/driver/node/credentialprovider/provider_pod.go, pkg/driver/node/credentialprovider/provider_test.go, pkg/driver/node/volumecontext/volume_context.go, pkg/podmounter/mppod/creator.go, pkg/podmounter/mppod/creator_test.go, tests/controller/controller_test.go, tests/e2e-kubernetes/testsuites/cache.go
This PR replaces `persistentVolumeClaim` cache type with `ephemeral`. If configured, the Mountpoint Pod will use a [generic ephemeral volume](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) to ensure each Mountpoint Pod gets its own cache volume. 
Given the following configuration:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: mp-cache-ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
type: io2
iopsPerGB: "256000"
blockExpress: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: s3-pv
spec:
csi:
driver: s3.csi.aws.com
volumeHandle: s3-pv
volumeAttributes:
bucketName: amzn-s3-demo-bucket
cache: ephemeral
cacheEphemeralStorageClassName: …
```
=> Support `ephemeral` volume type as local-cache instead of `persistentVolumeClaim` in Mountpoint Pod

.github/workflows/notify-slack.yaml
**Issue #, if available:**
None
**Description of changes:**
Added a new workflow file `.github/workflows/notify-slack.yaml` that sets up notifications for:
- Issues: When issues are opened, reopened, or edited
- Pull Requests: When PRs are opened, reopened, or updated with new commits
=> Slack notifications on PR's and Issues

.github/matrix.yaml
Adds AL2023 to the list of OS families to test on.
Tests: https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/15824618418
=> Add AL2023 to OS family

charts/aws-mountpoint-s3-csi-driver/templates/controller.yaml, charts/aws-mountpoint-s3-csi-driver/templates/mount-s3-priority.yaml, charts/aws-mountpoint-s3-csi-driver/templates/serviceaccount-csi-controller.yaml, charts/aws-mountpoint-s3-csi-driver/values.yaml, cmd/aws-s3-csi-controller/csicontroller/reconciler.go, cmd/aws-s3-csi-controller/main.go, docs/HEADROOM_FOR_MPPOD.md, docs/TROUBLESHOOTING.md, pkg/driver/node/mounter/pod_mounter.go, pkg/podmounter/mppod/creator.go, pkg/podmounter/mppod/creator_test.go, pkg/podmounter/mppod/headroom.go, pkg/podmounter/mppod/headroom_test.go, pkg/podmounter/mppod/watcher/watcher.go, pkg/podmounter/mppod/watcher/watcher_test.go, tests/controller/controller_test.go, tests/controller/suite_test.go, tests/e2e-kubernetes/e2e_test.go, tests/e2e-kubernetes/scripts/helm.sh, tests/e2e-kubernetes/testsuites/headroom.go
This PR adds an experimental feature for reserving headroom for Mountpoint Pods to help with issues like https://github.com/awslabs/mountpoint-s3-csi-driver/issues/534.
The CSI Driver v2 spawns Mountpoint Pods into the same nodes as the workloads to provide volumes. The CSI Driver spawns these Mountpoint Pods _after_ the workloads are assigned to nodes. This approach is taken because we might be able to [share an existing Mountpoint Pod](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/v2/docs/MOUNTPOINT_POD_SHARING.md) on a specific node, eliminating the need to spawn a new one. Therefore, the CSI Driver needs to wait until a workload is scheduled to a specific node before deciding whether to share an existing Mountpoint Pod or spawn a new one.
This dynamic spawning of Mountpoint …
=> Add support for reserving headroom for Mountpoint Pods

.github/workflows/e2e-tests.yaml, .github/workflows/e2e-upgrade-test.yaml, tests/e2e-kubernetes/scripts/run.sh, tests/e2e-kubernetes/testsuites/upgrade.go
This is a follow-up PR for https://github.com/awslabs/mountpoint-s3-csi-driver/pull/532 to fix problems with GitHub workflow. Triggered a successful upgrade test from 1.15.0 to 2.0.0-source on https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/16503618110.
---
=> Fixes on upgrade test GitHub workflow

Makefile, charts/aws-mountpoint-s3-csi-driver/templates/mountpoints3podattachments-crd.yaml, hack/patches/selectablefields-k8s-version.patch, tests/e2e-kubernetes/scripts/helm.sh
[Selectable fields for custom resources](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields) GA'd on Kubernetes 1.32. We [check Kubernetes version at the runtime](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/d9cc082b6c27922f4efb54b742b47841bd9fb590/pkg/cluster/cluster.go#L58-L70) before using this feature, but our Helm template contains this field regardless of the Kubernetes version. 
This could either cause a validation error or a warning ([as in our CI](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/16598473580/job/46952783952#step:9:151)) like:
```
I0729 14:24:39.116674    4077 warnings.go:110] "Warning: unknown field \"spec.versions[0].selectableFields\""
```
This PR also adds a new …
=> Gate `selectableFields` in CRD definition for Kubernetes <1.32

tests/e2e-kubernetes/scripts/run.sh, tests/e2e-kubernetes/testsuites/util.go
Max retries of 5 even [sometimes fails](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/16671525652/job/47189139429?pr=555#step:10:9055), this PR increases that to 10. Also, we get throttles as part of [our CI scripts as well](https://github.com/awslabs/mountpoint-s3-csi-driver/actions/runs/16671525652/job/47189139544?pr=555#step:8:98), this PR also applies some retry configuration to AWS CLI calls.
Also added `--github-output` to our Ginkgo calls to make output more friendly in GitHub console.
---
=> Increase max retries even further in CI and also apply to AWS CLI calls

charts/aws-mountpoint-s3-csi-driver/templates/NOTES.txt
This change introduces the first iteration of `NOTES.txt`, which is a template message shown following an install or upgrade of the Helm chart.
The initial content describes the version installed, where to learn what file system operations are supported, and also displays information about how the Mountpoint processes are updated during an upgrade.
Follow-up from this PR review: https://github.com/awslabs/mountpoint-s3-csi-driver/pull/596#pullrequestreview-3303661282
This is the output from an upgrade:
❯ helm upgrade --install aws-mountpoint-s3-csi-driver \
--namespace kube-system \
./charts/aws-mountpoint-s3-csi-driver
Release "aws-mountpoint-s3-csi-driver" has been upgraded. Happy Helming!
NAME: aws-mountpoint-s3-csi-driver
LAST …
=> Add Helm NOTES.txt for post-install/upgrade messages
